FROM node:lts-alpine3.15

RUN apk add chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

COPY avatar /srv/uploads/avatar
COPY app /app

WORKDIR /app

RUN npm install && npm run build

ENTRYPOINT [ "npm", "run", "start:prod" ]